/* eslint-disable react-native/no-inline-styles */
import React from 'react';
import { FlatList, Image, StatusBar, StyleSheet, Text, View } from 'react-native';
import { colors } from '../assets/colors';
import { fonts } from '../assets/fonts';
import { hp, sizeFont, wp } from '../assets/responsive';
import ButtonD from '../components/ButtonD';

const dataRepo = [
    {
        'id': 253201427,
        'node_id': 'MDEwOlJlcG9zaXRvcnkyNTMyMDE0Mjc=',
        'name': 'back-and-book',
        'full_name': 'ahmadsiddiq-lang/back-and-book',
        'private': false,
        'owner': {
            'login': 'ahmadsiddiq-lang',
            'id': 60493382,
            'node_id': 'MDQ6VXNlcjYwNDkzMzgy',
            'avatar_url': 'https://avatars.githubusercontent.com/u/60493382?v=4',
            'gravatar_id': '',
            'url': 'https://api.github.com/users/ahmadsiddiq-lang',
            'html_url': 'https://github.com/ahmadsiddiq-lang',
            'followers_url': 'https://api.github.com/users/ahmadsiddiq-lang/followers',
            'following_url': 'https://api.github.com/users/ahmadsiddiq-lang/following{/other_user}',
            'gists_url': 'https://api.github.com/users/ahmadsiddiq-lang/gists{/gist_id}',
            'starred_url': 'https://api.github.com/users/ahmadsiddiq-lang/starred{/owner}{/repo}',
            'subscriptions_url': 'https://api.github.com/users/ahmadsiddiq-lang/subscriptions',
            'organizations_url': 'https://api.github.com/users/ahmadsiddiq-lang/orgs',
            'repos_url': 'https://api.github.com/users/ahmadsiddiq-lang/repos',
            'events_url': 'https://api.github.com/users/ahmadsiddiq-lang/events{/privacy}',
            'received_events_url': 'https://api.github.com/users/ahmadsiddiq-lang/received_events',
            'type': 'User',
            'site_admin': false,
        },
        'html_url': 'https://github.com/ahmadsiddiq-lang/back-and-book',
        'description': null,
        'fork': false,
        'url': 'https://api.github.com/repos/ahmadsiddiq-lang/back-and-book',
        'forks_url': 'https://api.github.com/repos/ahmadsiddiq-lang/back-and-book/forks',
        'keys_url': 'https://api.github.com/repos/ahmadsiddiq-lang/back-and-book/keys{/key_id}',
        'collaborators_url': 'https://api.github.com/repos/ahmadsiddiq-lang/back-and-book/collaborators{/collaborator}',
        'teams_url': 'https://api.github.com/repos/ahmadsiddiq-lang/back-and-book/teams',
        'hooks_url': 'https://api.github.com/repos/ahmadsiddiq-lang/back-and-book/hooks',
        'issue_events_url': 'https://api.github.com/repos/ahmadsiddiq-lang/back-and-book/issues/events{/number}',
        'events_url': 'https://api.github.com/repos/ahmadsiddiq-lang/back-and-book/events',
        'assignees_url': 'https://api.github.com/repos/ahmadsiddiq-lang/back-and-book/assignees{/user}',
        'branches_url': 'https://api.github.com/repos/ahmadsiddiq-lang/back-and-book/branches{/branch}',
        'tags_url': 'https://api.github.com/repos/ahmadsiddiq-lang/back-and-book/tags',
        'blobs_url': 'https://api.github.com/repos/ahmadsiddiq-lang/back-and-book/git/blobs{/sha}',
        'git_tags_url': 'https://api.github.com/repos/ahmadsiddiq-lang/back-and-book/git/tags{/sha}',
        'git_refs_url': 'https://api.github.com/repos/ahmadsiddiq-lang/back-and-book/git/refs{/sha}',
        'trees_url': 'https://api.github.com/repos/ahmadsiddiq-lang/back-and-book/git/trees{/sha}',
        'statuses_url': 'https://api.github.com/repos/ahmadsiddiq-lang/back-and-book/statuses/{sha}',
        'languages_url': 'https://api.github.com/repos/ahmadsiddiq-lang/back-and-book/languages',
        'stargazers_url': 'https://api.github.com/repos/ahmadsiddiq-lang/back-and-book/stargazers',
        'contributors_url': 'https://api.github.com/repos/ahmadsiddiq-lang/back-and-book/contributors',
        'subscribers_url': 'https://api.github.com/repos/ahmadsiddiq-lang/back-and-book/subscribers',
        'subscription_url': 'https://api.github.com/repos/ahmadsiddiq-lang/back-and-book/subscription',
        'commits_url': 'https://api.github.com/repos/ahmadsiddiq-lang/back-and-book/commits{/sha}',
        'git_commits_url': 'https://api.github.com/repos/ahmadsiddiq-lang/back-and-book/git/commits{/sha}',
        'comments_url': 'https://api.github.com/repos/ahmadsiddiq-lang/back-and-book/comments{/number}',
        'issue_comment_url': 'https://api.github.com/repos/ahmadsiddiq-lang/back-and-book/issues/comments{/number}',
        'contents_url': 'https://api.github.com/repos/ahmadsiddiq-lang/back-and-book/contents/{+path}',
        'compare_url': 'https://api.github.com/repos/ahmadsiddiq-lang/back-and-book/compare/{base}...{head}',
        'merges_url': 'https://api.github.com/repos/ahmadsiddiq-lang/back-and-book/merges',
        'archive_url': 'https://api.github.com/repos/ahmadsiddiq-lang/back-and-book/{archive_format}{/ref}',
        'downloads_url': 'https://api.github.com/repos/ahmadsiddiq-lang/back-and-book/downloads',
        'issues_url': 'https://api.github.com/repos/ahmadsiddiq-lang/back-and-book/issues{/number}',
        'pulls_url': 'https://api.github.com/repos/ahmadsiddiq-lang/back-and-book/pulls{/number}',
        'milestones_url': 'https://api.github.com/repos/ahmadsiddiq-lang/back-and-book/milestones{/number}',
        'notifications_url': 'https://api.github.com/repos/ahmadsiddiq-lang/back-and-book/notifications{?since,all,participating}',
        'labels_url': 'https://api.github.com/repos/ahmadsiddiq-lang/back-and-book/labels{/name}',
        'releases_url': 'https://api.github.com/repos/ahmadsiddiq-lang/back-and-book/releases{/id}',
        'deployments_url': 'https://api.github.com/repos/ahmadsiddiq-lang/back-and-book/deployments',
        'created_at': '2020-04-05T09:47:07Z',
        'updated_at': '2020-05-11T02:05:56Z',
        'pushed_at': '2020-12-12T17:11:51Z',
        'git_url': 'git://github.com/ahmadsiddiq-lang/back-and-book.git',
        'ssh_url': 'git@github.com:ahmadsiddiq-lang/back-and-book.git',
        'clone_url': 'https://github.com/ahmadsiddiq-lang/back-and-book.git',
        'svn_url': 'https://github.com/ahmadsiddiq-lang/back-and-book',
        'homepage': null,
        'size': 2178,
        'stargazers_count': 0,
        'watchers_count': 0,
        'language': 'JavaScript',
        'has_issues': true,
        'has_projects': true,
        'has_downloads': true,
        'has_wiki': true,
        'has_pages': false,
        'forks_count': 0,
        'mirror_url': null,
        'archived': false,
        'disabled': false,
        'open_issues_count': 1,
        'license': null,
        'forks': 0,
        'open_issues': 1,
        'watchers': 0,
        'default_branch': 'master',
    },
    {
        'id': 258281628,
        'node_id': 'MDEwOlJlcG9zaXRvcnkyNTgyODE2Mjg=',
        'name': 'back-and-project',
        'full_name': 'ahmadsiddiq-lang/back-and-project',
        'private': false,
        'owner': {
            'login': 'ahmadsiddiq-lang',
            'id': 60493382,
            'node_id': 'MDQ6VXNlcjYwNDkzMzgy',
            'avatar_url': 'https://avatars.githubusercontent.com/u/60493382?v=4',
            'gravatar_id': '',
            'url': 'https://api.github.com/users/ahmadsiddiq-lang',
            'html_url': 'https://github.com/ahmadsiddiq-lang',
            'followers_url': 'https://api.github.com/users/ahmadsiddiq-lang/followers',
            'following_url': 'https://api.github.com/users/ahmadsiddiq-lang/following{/other_user}',
            'gists_url': 'https://api.github.com/users/ahmadsiddiq-lang/gists{/gist_id}',
            'starred_url': 'https://api.github.com/users/ahmadsiddiq-lang/starred{/owner}{/repo}',
            'subscriptions_url': 'https://api.github.com/users/ahmadsiddiq-lang/subscriptions',
            'organizations_url': 'https://api.github.com/users/ahmadsiddiq-lang/orgs',
            'repos_url': 'https://api.github.com/users/ahmadsiddiq-lang/repos',
            'events_url': 'https://api.github.com/users/ahmadsiddiq-lang/events{/privacy}',
            'received_events_url': 'https://api.github.com/users/ahmadsiddiq-lang/received_events',
            'type': 'User',
            'site_admin': false,
        },
        'html_url': 'https://github.com/ahmadsiddiq-lang/back-and-project',
        'description': null,
        'fork': false,
        'url': 'https://api.github.com/repos/ahmadsiddiq-lang/back-and-project',
        'forks_url': 'https://api.github.com/repos/ahmadsiddiq-lang/back-and-project/forks',
        'keys_url': 'https://api.github.com/repos/ahmadsiddiq-lang/back-and-project/keys{/key_id}',
        'collaborators_url': 'https://api.github.com/repos/ahmadsiddiq-lang/back-and-project/collaborators{/collaborator}',
        'teams_url': 'https://api.github.com/repos/ahmadsiddiq-lang/back-and-project/teams',
        'hooks_url': 'https://api.github.com/repos/ahmadsiddiq-lang/back-and-project/hooks',
        'issue_events_url': 'https://api.github.com/repos/ahmadsiddiq-lang/back-and-project/issues/events{/number}',
        'events_url': 'https://api.github.com/repos/ahmadsiddiq-lang/back-and-project/events',
        'assignees_url': 'https://api.github.com/repos/ahmadsiddiq-lang/back-and-project/assignees{/user}',
        'branches_url': 'https://api.github.com/repos/ahmadsiddiq-lang/back-and-project/branches{/branch}',
        'tags_url': 'https://api.github.com/repos/ahmadsiddiq-lang/back-and-project/tags',
        'blobs_url': 'https://api.github.com/repos/ahmadsiddiq-lang/back-and-project/git/blobs{/sha}',
        'git_tags_url': 'https://api.github.com/repos/ahmadsiddiq-lang/back-and-project/git/tags{/sha}',
        'git_refs_url': 'https://api.github.com/repos/ahmadsiddiq-lang/back-and-project/git/refs{/sha}',
        'trees_url': 'https://api.github.com/repos/ahmadsiddiq-lang/back-and-project/git/trees{/sha}',
        'statuses_url': 'https://api.github.com/repos/ahmadsiddiq-lang/back-and-project/statuses/{sha}',
        'languages_url': 'https://api.github.com/repos/ahmadsiddiq-lang/back-and-project/languages',
        'stargazers_url': 'https://api.github.com/repos/ahmadsiddiq-lang/back-and-project/stargazers',
        'contributors_url': 'https://api.github.com/repos/ahmadsiddiq-lang/back-and-project/contributors',
        'subscribers_url': 'https://api.github.com/repos/ahmadsiddiq-lang/back-and-project/subscribers',
        'subscription_url': 'https://api.github.com/repos/ahmadsiddiq-lang/back-and-project/subscription',
        'commits_url': 'https://api.github.com/repos/ahmadsiddiq-lang/back-and-project/commits{/sha}',
        'git_commits_url': 'https://api.github.com/repos/ahmadsiddiq-lang/back-and-project/git/commits{/sha}',
        'comments_url': 'https://api.github.com/repos/ahmadsiddiq-lang/back-and-project/comments{/number}',
        'issue_comment_url': 'https://api.github.com/repos/ahmadsiddiq-lang/back-and-project/issues/comments{/number}',
        'contents_url': 'https://api.github.com/repos/ahmadsiddiq-lang/back-and-project/contents/{+path}',
        'compare_url': 'https://api.github.com/repos/ahmadsiddiq-lang/back-and-project/compare/{base}...{head}',
        'merges_url': 'https://api.github.com/repos/ahmadsiddiq-lang/back-and-project/merges',
        'archive_url': 'https://api.github.com/repos/ahmadsiddiq-lang/back-and-project/{archive_format}{/ref}',
        'downloads_url': 'https://api.github.com/repos/ahmadsiddiq-lang/back-and-project/downloads',
        'issues_url': 'https://api.github.com/repos/ahmadsiddiq-lang/back-and-project/issues{/number}',
        'pulls_url': 'https://api.github.com/repos/ahmadsiddiq-lang/back-and-project/pulls{/number}',
        'milestones_url': 'https://api.github.com/repos/ahmadsiddiq-lang/back-and-project/milestones{/number}',
        'notifications_url': 'https://api.github.com/repos/ahmadsiddiq-lang/back-and-project/notifications{?since,all,participating}',
        'labels_url': 'https://api.github.com/repos/ahmadsiddiq-lang/back-and-project/labels{/name}',
        'releases_url': 'https://api.github.com/repos/ahmadsiddiq-lang/back-and-project/releases{/id}',
        'deployments_url': 'https://api.github.com/repos/ahmadsiddiq-lang/back-and-project/deployments',
        'created_at': '2020-04-23T17:33:24Z',
        'updated_at': '2020-04-27T07:18:50Z',
        'pushed_at': '2020-04-27T05:39:20Z',
        'git_url': 'git://github.com/ahmadsiddiq-lang/back-and-project.git',
        'ssh_url': 'git@github.com:ahmadsiddiq-lang/back-and-project.git',
        'clone_url': 'https://github.com/ahmadsiddiq-lang/back-and-project.git',
        'svn_url': 'https://github.com/ahmadsiddiq-lang/back-and-project',
        'homepage': null,
        'size': 1569,
        'stargazers_count': 0,
        'watchers_count': 0,
        'language': 'JavaScript',
        'has_issues': true,
        'has_projects': true,
        'has_downloads': true,
        'has_wiki': true,
        'has_pages': false,
        'forks_count': 0,
        'mirror_url': null,
        'archived': false,
        'disabled': false,
        'open_issues_count': 0,
        'license': null,
        'forks': 0,
        'open_issues': 0,
        'watchers': 0,
        'default_branch': 'master',
    },
    {
        'id': 249094784,
        'node_id': 'MDEwOlJlcG9zaXRvcnkyNDkwOTQ3ODQ=',
        'name': 'FamsChat-ReactNative-Firebase',
        'full_name': 'ahmadsiddiq-lang/FamsChat-ReactNative-Firebase',
        'private': false,
        'owner': {
            'login': 'ahmadsiddiq-lang',
            'id': 60493382,
            'node_id': 'MDQ6VXNlcjYwNDkzMzgy',
            'avatar_url': 'https://avatars.githubusercontent.com/u/60493382?v=4',
            'gravatar_id': '',
            'url': 'https://api.github.com/users/ahmadsiddiq-lang',
            'html_url': 'https://github.com/ahmadsiddiq-lang',
            'followers_url': 'https://api.github.com/users/ahmadsiddiq-lang/followers',
            'following_url': 'https://api.github.com/users/ahmadsiddiq-lang/following{/other_user}',
            'gists_url': 'https://api.github.com/users/ahmadsiddiq-lang/gists{/gist_id}',
            'starred_url': 'https://api.github.com/users/ahmadsiddiq-lang/starred{/owner}{/repo}',
            'subscriptions_url': 'https://api.github.com/users/ahmadsiddiq-lang/subscriptions',
            'organizations_url': 'https://api.github.com/users/ahmadsiddiq-lang/orgs',
            'repos_url': 'https://api.github.com/users/ahmadsiddiq-lang/repos',
            'events_url': 'https://api.github.com/users/ahmadsiddiq-lang/events{/privacy}',
            'received_events_url': 'https://api.github.com/users/ahmadsiddiq-lang/received_events',
            'type': 'User',
            'site_admin': false,
        },
        'html_url': 'https://github.com/ahmadsiddiq-lang/FamsChat-ReactNative-Firebase',
        'description': null,
        'fork': true,
        'url': 'https://api.github.com/repos/ahmadsiddiq-lang/FamsChat-ReactNative-Firebase',
        'forks_url': 'https://api.github.com/repos/ahmadsiddiq-lang/FamsChat-ReactNative-Firebase/forks',
        'keys_url': 'https://api.github.com/repos/ahmadsiddiq-lang/FamsChat-ReactNative-Firebase/keys{/key_id}',
        'collaborators_url': 'https://api.github.com/repos/ahmadsiddiq-lang/FamsChat-ReactNative-Firebase/collaborators{/collaborator}',
        'teams_url': 'https://api.github.com/repos/ahmadsiddiq-lang/FamsChat-ReactNative-Firebase/teams',
        'hooks_url': 'https://api.github.com/repos/ahmadsiddiq-lang/FamsChat-ReactNative-Firebase/hooks',
        'issue_events_url': 'https://api.github.com/repos/ahmadsiddiq-lang/FamsChat-ReactNative-Firebase/issues/events{/number}',
        'events_url': 'https://api.github.com/repos/ahmadsiddiq-lang/FamsChat-ReactNative-Firebase/events',
        'assignees_url': 'https://api.github.com/repos/ahmadsiddiq-lang/FamsChat-ReactNative-Firebase/assignees{/user}',
        'branches_url': 'https://api.github.com/repos/ahmadsiddiq-lang/FamsChat-ReactNative-Firebase/branches{/branch}',
        'tags_url': 'https://api.github.com/repos/ahmadsiddiq-lang/FamsChat-ReactNative-Firebase/tags',
        'blobs_url': 'https://api.github.com/repos/ahmadsiddiq-lang/FamsChat-ReactNative-Firebase/git/blobs{/sha}',
        'git_tags_url': 'https://api.github.com/repos/ahmadsiddiq-lang/FamsChat-ReactNative-Firebase/git/tags{/sha}',
        'git_refs_url': 'https://api.github.com/repos/ahmadsiddiq-lang/FamsChat-ReactNative-Firebase/git/refs{/sha}',
        'trees_url': 'https://api.github.com/repos/ahmadsiddiq-lang/FamsChat-ReactNative-Firebase/git/trees{/sha}',
        'statuses_url': 'https://api.github.com/repos/ahmadsiddiq-lang/FamsChat-ReactNative-Firebase/statuses/{sha}',
        'languages_url': 'https://api.github.com/repos/ahmadsiddiq-lang/FamsChat-ReactNative-Firebase/languages',
        'stargazers_url': 'https://api.github.com/repos/ahmadsiddiq-lang/FamsChat-ReactNative-Firebase/stargazers',
        'contributors_url': 'https://api.github.com/repos/ahmadsiddiq-lang/FamsChat-ReactNative-Firebase/contributors',
        'subscribers_url': 'https://api.github.com/repos/ahmadsiddiq-lang/FamsChat-ReactNative-Firebase/subscribers',
        'subscription_url': 'https://api.github.com/repos/ahmadsiddiq-lang/FamsChat-ReactNative-Firebase/subscription',
        'commits_url': 'https://api.github.com/repos/ahmadsiddiq-lang/FamsChat-ReactNative-Firebase/commits{/sha}',
        'git_commits_url': 'https://api.github.com/repos/ahmadsiddiq-lang/FamsChat-ReactNative-Firebase/git/commits{/sha}',
        'comments_url': 'https://api.github.com/repos/ahmadsiddiq-lang/FamsChat-ReactNative-Firebase/comments{/number}',
        'issue_comment_url': 'https://api.github.com/repos/ahmadsiddiq-lang/FamsChat-ReactNative-Firebase/issues/comments{/number}',
        'contents_url': 'https://api.github.com/repos/ahmadsiddiq-lang/FamsChat-ReactNative-Firebase/contents/{+path}',
        'compare_url': 'https://api.github.com/repos/ahmadsiddiq-lang/FamsChat-ReactNative-Firebase/compare/{base}...{head}',
        'merges_url': 'https://api.github.com/repos/ahmadsiddiq-lang/FamsChat-ReactNative-Firebase/merges',
        'archive_url': 'https://api.github.com/repos/ahmadsiddiq-lang/FamsChat-ReactNative-Firebase/{archive_format}{/ref}',
        'downloads_url': 'https://api.github.com/repos/ahmadsiddiq-lang/FamsChat-ReactNative-Firebase/downloads',
        'issues_url': 'https://api.github.com/repos/ahmadsiddiq-lang/FamsChat-ReactNative-Firebase/issues{/number}',
        'pulls_url': 'https://api.github.com/repos/ahmadsiddiq-lang/FamsChat-ReactNative-Firebase/pulls{/number}',
        'milestones_url': 'https://api.github.com/repos/ahmadsiddiq-lang/FamsChat-ReactNative-Firebase/milestones{/number}',
        'notifications_url': 'https://api.github.com/repos/ahmadsiddiq-lang/FamsChat-ReactNative-Firebase/notifications{?since,all,participating}',
        'labels_url': 'https://api.github.com/repos/ahmadsiddiq-lang/FamsChat-ReactNative-Firebase/labels{/name}',
        'releases_url': 'https://api.github.com/repos/ahmadsiddiq-lang/FamsChat-ReactNative-Firebase/releases{/id}',
        'deployments_url': 'https://api.github.com/repos/ahmadsiddiq-lang/FamsChat-ReactNative-Firebase/deployments',
        'created_at': '2020-03-22T01:54:02Z',
        'updated_at': '2020-03-22T01:54:04Z',
        'pushed_at': '2020-03-20T18:55:19Z',
        'git_url': 'git://github.com/ahmadsiddiq-lang/FamsChat-ReactNative-Firebase.git',
        'ssh_url': 'git@github.com:ahmadsiddiq-lang/FamsChat-ReactNative-Firebase.git',
        'clone_url': 'https://github.com/ahmadsiddiq-lang/FamsChat-ReactNative-Firebase.git',
        'svn_url': 'https://github.com/ahmadsiddiq-lang/FamsChat-ReactNative-Firebase',
        'homepage': null,
        'size': 19285,
        'stargazers_count': 0,
        'watchers_count': 0,
        'language': null,
        'has_issues': false,
        'has_projects': true,
        'has_downloads': true,
        'has_wiki': true,
        'has_pages': false,
        'forks_count': 1,
        'mirror_url': null,
        'archived': false,
        'disabled': false,
        'open_issues_count': 0,
        'license': null,
        'forks': 1,
        'open_issues': 0,
        'watchers': 0,
        'default_branch': 'master',
    },
    {
        'id': 247226495,
        'node_id': 'MDEwOlJlcG9zaXRvcnkyNDcyMjY0OTU=',
        'name': 'gochat',
        'full_name': 'ahmadsiddiq-lang/gochat',
        'private': false,
        'owner': {
            'login': 'ahmadsiddiq-lang',
            'id': 60493382,
            'node_id': 'MDQ6VXNlcjYwNDkzMzgy',
            'avatar_url': 'https://avatars.githubusercontent.com/u/60493382?v=4',
            'gravatar_id': '',
            'url': 'https://api.github.com/users/ahmadsiddiq-lang',
            'html_url': 'https://github.com/ahmadsiddiq-lang',
            'followers_url': 'https://api.github.com/users/ahmadsiddiq-lang/followers',
            'following_url': 'https://api.github.com/users/ahmadsiddiq-lang/following{/other_user}',
            'gists_url': 'https://api.github.com/users/ahmadsiddiq-lang/gists{/gist_id}',
            'starred_url': 'https://api.github.com/users/ahmadsiddiq-lang/starred{/owner}{/repo}',
            'subscriptions_url': 'https://api.github.com/users/ahmadsiddiq-lang/subscriptions',
            'organizations_url': 'https://api.github.com/users/ahmadsiddiq-lang/orgs',
            'repos_url': 'https://api.github.com/users/ahmadsiddiq-lang/repos',
            'events_url': 'https://api.github.com/users/ahmadsiddiq-lang/events{/privacy}',
            'received_events_url': 'https://api.github.com/users/ahmadsiddiq-lang/received_events',
            'type': 'User',
            'site_admin': false,
        },
        'html_url': 'https://github.com/ahmadsiddiq-lang/gochat',
        'description': null,
        'fork': false,
        'url': 'https://api.github.com/repos/ahmadsiddiq-lang/gochat',
        'forks_url': 'https://api.github.com/repos/ahmadsiddiq-lang/gochat/forks',
        'keys_url': 'https://api.github.com/repos/ahmadsiddiq-lang/gochat/keys{/key_id}',
        'collaborators_url': 'https://api.github.com/repos/ahmadsiddiq-lang/gochat/collaborators{/collaborator}',
        'teams_url': 'https://api.github.com/repos/ahmadsiddiq-lang/gochat/teams',
        'hooks_url': 'https://api.github.com/repos/ahmadsiddiq-lang/gochat/hooks',
        'issue_events_url': 'https://api.github.com/repos/ahmadsiddiq-lang/gochat/issues/events{/number}',
        'events_url': 'https://api.github.com/repos/ahmadsiddiq-lang/gochat/events',
        'assignees_url': 'https://api.github.com/repos/ahmadsiddiq-lang/gochat/assignees{/user}',
        'branches_url': 'https://api.github.com/repos/ahmadsiddiq-lang/gochat/branches{/branch}',
        'tags_url': 'https://api.github.com/repos/ahmadsiddiq-lang/gochat/tags',
        'blobs_url': 'https://api.github.com/repos/ahmadsiddiq-lang/gochat/git/blobs{/sha}',
        'git_tags_url': 'https://api.github.com/repos/ahmadsiddiq-lang/gochat/git/tags{/sha}',
        'git_refs_url': 'https://api.github.com/repos/ahmadsiddiq-lang/gochat/git/refs{/sha}',
        'trees_url': 'https://api.github.com/repos/ahmadsiddiq-lang/gochat/git/trees{/sha}',
        'statuses_url': 'https://api.github.com/repos/ahmadsiddiq-lang/gochat/statuses/{sha}',
        'languages_url': 'https://api.github.com/repos/ahmadsiddiq-lang/gochat/languages',
        'stargazers_url': 'https://api.github.com/repos/ahmadsiddiq-lang/gochat/stargazers',
        'contributors_url': 'https://api.github.com/repos/ahmadsiddiq-lang/gochat/contributors',
        'subscribers_url': 'https://api.github.com/repos/ahmadsiddiq-lang/gochat/subscribers',
        'subscription_url': 'https://api.github.com/repos/ahmadsiddiq-lang/gochat/subscription',
        'commits_url': 'https://api.github.com/repos/ahmadsiddiq-lang/gochat/commits{/sha}',
        'git_commits_url': 'https://api.github.com/repos/ahmadsiddiq-lang/gochat/git/commits{/sha}',
        'comments_url': 'https://api.github.com/repos/ahmadsiddiq-lang/gochat/comments{/number}',
        'issue_comment_url': 'https://api.github.com/repos/ahmadsiddiq-lang/gochat/issues/comments{/number}',
        'contents_url': 'https://api.github.com/repos/ahmadsiddiq-lang/gochat/contents/{+path}',
        'compare_url': 'https://api.github.com/repos/ahmadsiddiq-lang/gochat/compare/{base}...{head}',
        'merges_url': 'https://api.github.com/repos/ahmadsiddiq-lang/gochat/merges',
        'archive_url': 'https://api.github.com/repos/ahmadsiddiq-lang/gochat/{archive_format}{/ref}',
        'downloads_url': 'https://api.github.com/repos/ahmadsiddiq-lang/gochat/downloads',
        'issues_url': 'https://api.github.com/repos/ahmadsiddiq-lang/gochat/issues{/number}',
        'pulls_url': 'https://api.github.com/repos/ahmadsiddiq-lang/gochat/pulls{/number}',
        'milestones_url': 'https://api.github.com/repos/ahmadsiddiq-lang/gochat/milestones{/number}',
        'notifications_url': 'https://api.github.com/repos/ahmadsiddiq-lang/gochat/notifications{?since,all,participating}',
        'labels_url': 'https://api.github.com/repos/ahmadsiddiq-lang/gochat/labels{/name}',
        'releases_url': 'https://api.github.com/repos/ahmadsiddiq-lang/gochat/releases{/id}',
        'deployments_url': 'https://api.github.com/repos/ahmadsiddiq-lang/gochat/deployments',
        'created_at': '2020-03-14T06:45:59Z',
        'updated_at': '2020-03-30T08:29:42Z',
        'pushed_at': '2021-05-11T14:32:26Z',
        'git_url': 'git://github.com/ahmadsiddiq-lang/gochat.git',
        'ssh_url': 'git@github.com:ahmadsiddiq-lang/gochat.git',
        'clone_url': 'https://github.com/ahmadsiddiq-lang/gochat.git',
        'svn_url': 'https://github.com/ahmadsiddiq-lang/gochat',
        'homepage': null,
        'size': 14297,
        'stargazers_count': 0,
        'watchers_count': 0,
        'language': 'JavaScript',
        'has_issues': true,
        'has_projects': true,
        'has_downloads': true,
        'has_wiki': true,
        'has_pages': false,
        'forks_count': 0,
        'mirror_url': null,
        'archived': false,
        'disabled': false,
        'open_issues_count': 5,
        'license': null,
        'forks': 0,
        'open_issues': 5,
        'watchers': 0,
        'default_branch': 'master',
    },
    {
        'id': 270885087,
        'node_id': 'MDEwOlJlcG9zaXRvcnkyNzA4ODUwODc=',
        'name': 'google-signin',
        'full_name': 'ahmadsiddiq-lang/google-signin',
        'private': false,
        'owner': {
            'login': 'ahmadsiddiq-lang',
            'id': 60493382,
            'node_id': 'MDQ6VXNlcjYwNDkzMzgy',
            'avatar_url': 'https://avatars.githubusercontent.com/u/60493382?v=4',
            'gravatar_id': '',
            'url': 'https://api.github.com/users/ahmadsiddiq-lang',
            'html_url': 'https://github.com/ahmadsiddiq-lang',
            'followers_url': 'https://api.github.com/users/ahmadsiddiq-lang/followers',
            'following_url': 'https://api.github.com/users/ahmadsiddiq-lang/following{/other_user}',
            'gists_url': 'https://api.github.com/users/ahmadsiddiq-lang/gists{/gist_id}',
            'starred_url': 'https://api.github.com/users/ahmadsiddiq-lang/starred{/owner}{/repo}',
            'subscriptions_url': 'https://api.github.com/users/ahmadsiddiq-lang/subscriptions',
            'organizations_url': 'https://api.github.com/users/ahmadsiddiq-lang/orgs',
            'repos_url': 'https://api.github.com/users/ahmadsiddiq-lang/repos',
            'events_url': 'https://api.github.com/users/ahmadsiddiq-lang/events{/privacy}',
            'received_events_url': 'https://api.github.com/users/ahmadsiddiq-lang/received_events',
            'type': 'User',
            'site_admin': false,
        },
        'html_url': 'https://github.com/ahmadsiddiq-lang/google-signin',
        'description': 'Google Sign-in for your React Native applications',
        'fork': true,
        'url': 'https://api.github.com/repos/ahmadsiddiq-lang/google-signin',
        'forks_url': 'https://api.github.com/repos/ahmadsiddiq-lang/google-signin/forks',
        'keys_url': 'https://api.github.com/repos/ahmadsiddiq-lang/google-signin/keys{/key_id}',
        'collaborators_url': 'https://api.github.com/repos/ahmadsiddiq-lang/google-signin/collaborators{/collaborator}',
        'teams_url': 'https://api.github.com/repos/ahmadsiddiq-lang/google-signin/teams',
        'hooks_url': 'https://api.github.com/repos/ahmadsiddiq-lang/google-signin/hooks',
        'issue_events_url': 'https://api.github.com/repos/ahmadsiddiq-lang/google-signin/issues/events{/number}',
        'events_url': 'https://api.github.com/repos/ahmadsiddiq-lang/google-signin/events',
        'assignees_url': 'https://api.github.com/repos/ahmadsiddiq-lang/google-signin/assignees{/user}',
        'branches_url': 'https://api.github.com/repos/ahmadsiddiq-lang/google-signin/branches{/branch}',
        'tags_url': 'https://api.github.com/repos/ahmadsiddiq-lang/google-signin/tags',
        'blobs_url': 'https://api.github.com/repos/ahmadsiddiq-lang/google-signin/git/blobs{/sha}',
        'git_tags_url': 'https://api.github.com/repos/ahmadsiddiq-lang/google-signin/git/tags{/sha}',
        'git_refs_url': 'https://api.github.com/repos/ahmadsiddiq-lang/google-signin/git/refs{/sha}',
        'trees_url': 'https://api.github.com/repos/ahmadsiddiq-lang/google-signin/git/trees{/sha}',
        'statuses_url': 'https://api.github.com/repos/ahmadsiddiq-lang/google-signin/statuses/{sha}',
        'languages_url': 'https://api.github.com/repos/ahmadsiddiq-lang/google-signin/languages',
        'stargazers_url': 'https://api.github.com/repos/ahmadsiddiq-lang/google-signin/stargazers',
        'contributors_url': 'https://api.github.com/repos/ahmadsiddiq-lang/google-signin/contributors',
        'subscribers_url': 'https://api.github.com/repos/ahmadsiddiq-lang/google-signin/subscribers',
        'subscription_url': 'https://api.github.com/repos/ahmadsiddiq-lang/google-signin/subscription',
        'commits_url': 'https://api.github.com/repos/ahmadsiddiq-lang/google-signin/commits{/sha}',
        'git_commits_url': 'https://api.github.com/repos/ahmadsiddiq-lang/google-signin/git/commits{/sha}',
        'comments_url': 'https://api.github.com/repos/ahmadsiddiq-lang/google-signin/comments{/number}',
        'issue_comment_url': 'https://api.github.com/repos/ahmadsiddiq-lang/google-signin/issues/comments{/number}',
        'contents_url': 'https://api.github.com/repos/ahmadsiddiq-lang/google-signin/contents/{+path}',
        'compare_url': 'https://api.github.com/repos/ahmadsiddiq-lang/google-signin/compare/{base}...{head}',
        'merges_url': 'https://api.github.com/repos/ahmadsiddiq-lang/google-signin/merges',
        'archive_url': 'https://api.github.com/repos/ahmadsiddiq-lang/google-signin/{archive_format}{/ref}',
        'downloads_url': 'https://api.github.com/repos/ahmadsiddiq-lang/google-signin/downloads',
        'issues_url': 'https://api.github.com/repos/ahmadsiddiq-lang/google-signin/issues{/number}',
        'pulls_url': 'https://api.github.com/repos/ahmadsiddiq-lang/google-signin/pulls{/number}',
        'milestones_url': 'https://api.github.com/repos/ahmadsiddiq-lang/google-signin/milestones{/number}',
        'notifications_url': 'https://api.github.com/repos/ahmadsiddiq-lang/google-signin/notifications{?since,all,participating}',
        'labels_url': 'https://api.github.com/repos/ahmadsiddiq-lang/google-signin/labels{/name}',
        'releases_url': 'https://api.github.com/repos/ahmadsiddiq-lang/google-signin/releases{/id}',
        'deployments_url': 'https://api.github.com/repos/ahmadsiddiq-lang/google-signin/deployments',
        'created_at': '2020-06-09T02:34:38Z',
        'updated_at': '2020-10-14T20:15:45Z',
        'pushed_at': '2020-06-08T13:19:00Z',
        'git_url': 'git://github.com/ahmadsiddiq-lang/google-signin.git',
        'ssh_url': 'git@github.com:ahmadsiddiq-lang/google-signin.git',
        'clone_url': 'https://github.com/ahmadsiddiq-lang/google-signin.git',
        'svn_url': 'https://github.com/ahmadsiddiq-lang/google-signin',
        'homepage': '',
        'size': 21357,
        'stargazers_count': 0,
        'watchers_count': 0,
        'language': null,
        'has_issues': false,
        'has_projects': true,
        'has_downloads': true,
        'has_wiki': false,
        'has_pages': false,
        'forks_count': 0,
        'mirror_url': null,
        'archived': false,
        'disabled': false,
        'open_issues_count': 0,
        'license': {
            'key': 'mit',
            'name': 'MIT License',
            'spdx_id': 'MIT',
            'url': 'https://api.github.com/licenses/mit',
            'node_id': 'MDc6TGljZW5zZTEz',
        },
        'forks': 0,
        'open_issues': 0,
        'watchers': 0,
        'default_branch': 'master',
    },
];

export default function Home({ navigation }) {


    const renderItem = ({ item }) => {
        return (
            <View style={{
                marginBottom: hp(4),
                paddingBottom: hp(2),
                borderBottomWidth: 2,
                borderColor: colors.border3,
            }}>
                <Text style={{
                    fontSize: sizeFont(3.6),
                    fontFamily: fonts.Medium,
                    color: colors.fontBlue,
                }}>{item.name}</Text>
                {
                    item.language &&
                    <Text style={{
                        color: colors.fontBlack1,
                    }}>Language :
                <Text style={{
                            fontSize: sizeFont(3.5),
                            color: colors.fontBlack,
                        }}> {item.language}</Text>
                    </Text>
                }
            </View>
        );
    };

    return (
        <View style={styles.container}>
            <StatusBar backgroundColor={colors.bgWhite} barStyle="dark-content" />
            <View style={styles.head}>
                <View style={{
                    flexDirection: 'row',
                    alignItems: 'center',
                }}>
                    <View style={styles.boxImage}>
                        <Image source={require('../assets/images/User.png')}
                            style={styles.image}
                        />
                    </View>
                    <View style={{
                        marginLeft: wp(3),
                    }}>
                        <Text style={{
                            fontSize: sizeFont(4),
                            fontFamily: fonts.Medium,
                        }}>Ahmad Siddiq</Text>
                        <Text>ahmadsiddiq-lang</Text>
                    </View>
                </View>
                <View>
                    <ButtonD
                        onPress={() => navigation.navigate('Profile')}
                    >Profile</ButtonD>
                </View>
            </View>
            <View style={styles.content}>
                <View style={{
                    marginLeft: wp(3),
                    flexDirection: 'row',
                    marginVertical: wp(3),
                }}>
                    <View style={{ borderBottomWidth: 2, borderColor: colors.border1 }}>
                        <Text style={{
                            fontSize: sizeFont(4),
                            fontFamily: fonts.Medium,
                        }}>Repositories</Text>
                    </View>
                </View>
                <FlatList
                    data={dataRepo}
                    keyExtractor={(_, index) => index.toString()}
                    renderItem={renderItem}
                    contentContainerStyle={{
                        paddingHorizontal: wp(3),
                    }}
                />
            </View>
        </View>
    );
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
    },
    head: {
        paddingHorizontal: wp(3),
        paddingVertical: wp(5),
        backgroundColor: colors.bgWhite,
        elevation: 3,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    image: {
        resizeMode: 'cover',
        width: '100%',
        height: '100%',
    },
    boxImage: {
        width: wp(20),
        height: wp(20),
        borderRadius: 100,
        overflow: 'hidden',
        alignItems: 'center',
        justifyContent: 'center',
    },
    content: {
        flex: 1,
        backgroundColor: colors.bgWhite,
    },
});
